### ISSUE TITLE
[BUG] ZeroDivisionError

### ISSUE THREAD

**Issue by elgw** [ggirelli/radiantkit#110]
**Describe the bug**
nd2_to_tiff crashed with 
```
ZeroDivisionError: float division by zero
```

**Expected behaviour**
Warn that metadata is weird but continue.

**To Reproduce**
```
radiant nd2_to_tiff --deltaZ=0.3 iEG701_zYLA4.2_25X_201112_001.nd2
```

**Screenshots**
```
$ for f in $files; do radiant nd2_to_tiff --deltaZ 0.3 $f; done
11/16/2020 12:34:43 [P15712:nd2_to_tiff:run] INFO: Enforcing a deltaZ of 0.300 um.
11/16/2020 12:34:43 [P15712:conversion:log_details] INFO: Found 1 field(s) of view, with 2 channel(s).
11/16/2020 12:34:43 [P15712:conversion:log_details] INFO: Channels: ['dapi', 'a647'].
11/16/2020 12:34:43 [P15712:conversion:log_details] INFO: XYZ size: 2048 x 2048 x 85
11/16/2020 12:34:43 [P15712:conversion:log_details] INFO: Delta Z value(s): {0.3}
11/16/2020 12:34:43 [P15712:nd2_to_tiff:run] INFO: Output directory: 'iEG701_zYLA4.2_25X_201112_001'
Traceback (most recent call last):
  File "/home/erikw/.local/bin/radiant", line 8, in <module>
    sys.exit(main())
  File "/home/erikw/.local/pipx/venvs/radiantkit/lib/python3.8/site-packages/radiantkit/scripts/radiant.py", line 68, in main
    args.run(args)
  File "/home/erikw/.local/pipx/venvs/radiantkit/lib/python3.8/site-packages/radiantkit/scripts/nd2_to_tiff.py", line 342, in run
    convert_to_tiff(args, nd2I)
  File "/home/erikw/.local/pipx/venvs/radiantkit/lib/python3.8/site-packages/radiantkit/scripts/nd2_to_tiff.py", line 302, in convert_to_tiff
    export_field(args, nd2I, 0, args.channels)
  File "/home/erikw/.local/pipx/venvs/radiantkit/lib/python3.8/site-packages/radiantkit/scripts/nd2_to_tiff.py", line 245, in export_field
    export_multiple_channels(nd2I, field_id, args, channels, resolutionZ)
  File "/home/erikw/.local/pipx/venvs/radiantkit/lib/python3.8/site-packages/radiantkit/scripts/nd2_to_tiff.py", line 218, in export_multiple_channels
    export_single_channel(
  File "/home/erikw/.local/pipx/venvs/radiantkit/lib/python3.8/site-packages/radiantkit/scripts/nd2_to_tiff.py", line 163, in export_single_channel
    resolutionXY = (1 / metadata["pixel_microns"], 1 / metadata["pixel_microns"])
ZeroDivisionError: float division by zero
```

**Additional context**
```
$ radiant --version
/home/erikw/.local/bin/radiant 0.0.1
```

**Comment by ggirelli** [comment]
Apparently the metadata of the nd2 file reports an XY resolution of 0, which is currently not supported.

I will (1) look into the nd2 file and (2) add a check for this and an option to skip this (although I would not advise that).

**Comment by ggirelli** [comment]
Fixed this in `v0,0,1,16Nov2020` (merged to `main` branch). This is most likely due to an incorrect setup of the objective in the NIKON software and should be rectified. The following warning is now raised when this happens:
```XY resolution set to 0! (possibly incorrect obj. setup)```
The image is properly converted and the physical size of X and Y axes is set to 0.
